name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, edited]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    if: (github.event.action != 'closed' || github.event.pull_request.merged == true)
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11 ] # list of os: https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v3
        - run: |
            git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

        - uses: actions/setup-go@v3
          with:
            go-version: 1.18.x

        - name: Golang-ci install
          run: make lintci-deps

        - uses: actions/cache@v3
          with:
            path: |
              ~/.cache/go-build
              ~/Library/Caches/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: ${{ runner.os }}-go-

        - name: Lint
          run: make lint

        - name: Test
          run: make test

        - name: Data race tests
          run: make test-race
        
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            file: ./cover.out

        - name: Reproducible build test
          run: |
            go build -o batch            
            shasum -a256 ./batch > batch.sha256
            go build -o batch1
            shasum -a256 ./batch1 > batch1.sha256
            if ! cmp -s batch.sha256 batch1.sha256; then
              echo >&2 "Reproducible build broken"; cat batch.sha256; cat batch1.sha256; exit 1
            fi
